export const FONT_FAMILIES = [
  "Birthstone Bounce",
  "Blinker",
  "Cinzel Decorative",
  "Comic Neue",
  "Corinthia",
  "Cormorant Upright",
  "Dancing Script",
  "Dosis",
  "EB Garamond",
  "Fraunces",
  "Gluten",
  "Grenze Gotisch",
  "Inconsolata",
  "Lobster Two",
  "Merienda",
  "Oleo Script Swash Caps",
  "Orbitron",
  "Oswald",
  "Red Rose",
  "Roboto",
  "Sansita Swashed",
  "Shantell Sans",
  "The Nautigal",
  "Tomorrow",
  "Yanone Kaffeesatz",
];
